name: CI/CD Pipeline - Docker Build

on:
  push:
    branches:
      - main
      - teste_projetinho
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Testar aplicação (exemplo)
      run: |
        echo "Rodando testes (simulado)"
        # Aqui você pode rodar `pytest`, por exemplo
        # pytest

    - name: Build da imagem Docker
      run: |
        docker build -t projetinho .

    - name: Verificar se container roda
      run: |
        docker run -d -p 5000:5000 projetinho
