name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: nekas27/projetinho:latest

    - name: Download artifact from previous workflow
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
        path: ./artifacts

    - name: Display structure of downloaded files
      run: ls -R ./artifacts
